version: "3"
services:
  web:
    image: spring_backend_8293
    build: .
    ports:
      - "8293:8293"
    volumes:
      - persistent_volume:/app/volumes
    restart: unless-stopped
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/tri2_t2_8293/volumes
