version: '3'
services:
  web:
    image: spring_backend
    build: .
    ports:
      - "8087:8087"
    volumes:
      - persistent_volume:/app/volumes
    restart: unless-stopped
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/t8087_sera/volumes
