version: '3'
services:
  web:
    image: spring_backend_8192
    build: .
    ports:
      - "8192:8192"
    volumes:
      - persistent_volume:/app/volumes
    restart: unless-stopped
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/t8192_backend/volumes
