name: Deploy to Server
on: [push]
jobs:
  AWS-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo $\{\{ secrets.SSH_KEY \}\} | base64 -di > key.pem
      - run: chmod 400 key.pem
      - run: ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@[34.205.167.218] 'cd ~/[tri2_t2_8192]; git pull; docker-compose down; docker-compose up -d --build'
